# Generated by Django 5.2.7 on 2025-10-03 21:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('orange', 'Orange'), ('yellow', 'Yellow')], default='blue', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Postponed', 'Postponed'), ('Finished', 'Finished')], default='Started', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('speaking_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='transcript.transcript')),
            ],
            options={
                'ordering': ['-speaking_percentage'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_tags', to='transcript.tag')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_tags', to='transcript.transcript')),
            ],
            options={
                'unique_together': {('transcript', 'tag')},
            },
        ),
    ]
