# Generated by Django 5.2.7 on 2025-10-06 12:16

from django.db import migrations
from django.core.management import call_command


def import_transcripts(apps, schema_editor):
    """Import transcript files after migration"""
    try:
        call_command('import_transcripts')
    except Exception as e:
        # Log the error but don't fail the migration
        print(f"Warning: Failed to import transcripts: {e}")


def reverse_import_transcripts(apps, schema_editor):
    """Reverse operation - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_transcripts, reverse_import_transcripts),
    ]
